services:
  qbittorrent:
        image: linuxserver/qbittorrent:latest
        container_name: qbittorrent
        restart: unless-stopped
        ports:
          - "8080:8080"
          - "6881:6881"
          - "6881:6881/udp"   
        environment:
          - PUID=1000
          - PGID=1000
          - WEBUI_PORT=8080
        volumes:
          #make sure to change the directory mapped to downloads to wherever you want torrenting downloads to end up on your system
          #when you go to download something through the web ui you interact with this directory using the "downloads" directory that docker has mapped it to
          - ./config:/config
          - ../../mediaDrive/torrentingDownloads:/downloads
